### ISSUE TITLE
Manually include the css files in our <head> </head> ?

### ISSUE THREAD

**Issue by marcoczen** [Natshah/bootstrap-print#4]
Hi,

Instead of composer , can we just manually include the css files in our < head > ...  < /head > ?
For the bootstrap col-md-*, we just need ;

bootstrap-print-md.css 
bootstrap-print-md.css.map
bootstrap-print-md.min.css

Possible ?

**Comment by Natshah** [comment]
https://github.com/Natshah/bootstrap-print/blob/3.1.x/README.md

**Comment by marcoczen** [comment]
Hi ... Some time .. just saw your reply ... But the link you gave does not seem to answer the question ?
Can we manually include the needed css into head section of our file ?
Possible ?
